### PR TITLE
Commit with working additional functions.

### PR DESCRIPTION
**Pull request by anbhole**
I have added four additional functions for sending and receiving - 

    public native int nn_sendstr(int socket, String str, int flags);
    
    public native int nn_sendbyt(int socket, byte[] str, int flags);
    
    public native String nn_recvstr(int socket, int flags);
    
    public native byte[] nn_recvbyt(int socket, int flags);

The nn_recvstr and nn_recvbyt are useful to retrieving the entire message (using NN_MSG). The nn_sendstr and nn_sendbyt are corresponding send functions.

One more additional function is - 

    public native int nn_setsockopt_str(int socket, int level, int optidx,String optval);
for setting string options on socket.

Also I have added error codes to NanoLibrary.java.

### CODE REVIEW

**Comment by gonzus** [comment]
A couple of comments / questions:
1. The code still has debugging statements, please get rid of them.
2. Why should the new send/recv functions be native? Couldn't you implement them in Java?
3. There is no reason for naming a function nn_sendbyt(); if this patch goes through, I would rather name that function nn_sendbyte() (and same for recv).
4. You are also adding a bunch of error number constants. Perhaps you could split this patch into two (or even three, for nn_setsockopt_str()) separate pull requests.

Thanks for your contribution. Cheers,
Gonzalo

**Comment by anbhole** [comment]
1. Sure will do.
2. The issue with using the ByteBuffer is that it requires buffer size to be allocated before hand and if the message exceeds the buffer size, it will be truncated and there is no way to retrieve the rest of the message. The way to guarantee reading the entire message is by using zero copy buffers.
3. Yes I can rename them
4. Okay I will split them into three.

Regards,
Abhijit.

**Comment by gonzus** [comment]
Understood, native code applies then. Please go ahead with the three separate pull requests. Thanks again!

**Comment by anbhole** [comment]
Done the required changes.

**Comment by gonzus** [comment]
Merged, thank you for your work.

**Pull request merged**
