### PR TITLE
fix security issue 4

### PR DESCRIPTION
**Pull request by megahall**
This is a sketch of how to fix the big security issue #4 .

I didn't get a chance to fully test it yet, still working on it.

### CODE REVIEW

**Comment by megahall** [comment]
Tested it in my application, seems to work properly.

**Comment by megahall** [comment]
@gonzus Ping

**Comment by gonzus** [comment]
Pong... hold on.

**Comment by gonzus** [comment]
In a nutshell, you are using ByteBuffer's own methods for all Java buffer management... Looks good to me, more idiomatic and, of course, correct. Will pull.

**Comment by gonzus** [comment]
Merged.

**Pull request merged**
